#the original source of this file can be found in tools repository change it ther
# changes in tools|csg tiggered a full rebuild
# changes in csgapps|csg-manual|csg-tutorials only trigger tools+csg+ifself

language: cpp

sudo: false

addons:
  apt:
    sources:
      - boost-latest 
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - gcc-4.8
      - g++-4.8
      - libfftw3-dev
      - cmake
      - cmake-data
      - libgsl0-dev
      - txt2tags
      - libboost1.55-all-dev
      - libexpat1-dev
      - libsqlite3-dev
      - libhdf5-serial-dev
      - pkg-config
      - pgf
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-latex-recommended
      - cm-super
      - doxygen
      - graphviz
      - python-numpy
      - gnuplot-nox
      - octave

env:
  global:
    - HDF5_VERSION=1.8.18
    - GMX_MAX_THREADS=4
    - CSG_MDRUN_OPTS="-ntmpi 4"
    - CCACHE_CPP2=yes #for clang
    - GVER=4.8
  matrix: #NINJA=1 is currently not support by Travis' cmake, enable when >=2.8.9
    - CTP=yes WERROR=yes J=4
    - CTP=yes WALL=yes J=4
    - XTP=yes BDIR=build WERROR=yes J=4 TYPE=Debug
    - XTP=yes BDIR=build WALL=yes J=4 TYPE=Debug
    - XTP=yes BDIR=build WERROR=yes J=4 TYPE=Release
    - XTP=yes BDIR=build WALL=yes J=4 TYPE=Release MAN=yes
    - WALL=yes GMX_DOUBLE=yes J=4
    - WALL=yes GMX_VERSION=5.1 J=4
    - WALL=yes GMX_VERSION=5.1 GMX_DOUBLE=yes J=4
    - WALL=yes GMX_VERSION=9999 J=4
    - WALL=yes GMX_VERSION=9999 GMX_DOUBLE=yes J=4
    - MINIMAL=yes J=4
    - CSG_MDRUN_STEPS=500 TEST=hexane/ibi_bonded J=4
    - CSG_MDRUN_STEPS=500 TEST=hexane/ibi J=4
    - CSG_MDRUN_STEPS=500 TEST=methanol/ibi J=4
    - CSG_MDRUN_STEPS=5000 TEST=methanol/imc J=4
    - CSG_MDRUN_STEPS=2500 TEST=methanol-water/X_0.938/re J=4
    - CSG_MDRUN_STEPS=500 TEST=methanol-water/X_0.938/simplex J=4
    - CSG_MDRUN_STEPS=2500 TEST=methanol-water/X_0.062/re J=4
    - CSG_MDRUN_STEPS=500 TEST=methanol-water/X_0.062/simplex J=4
    - CSG_MDRUN_STEPS=2500 TEST=methanol-water/X_0.5/re J=4
    - CSG_MDRUN_STEPS=500 TEST=methanol-water/X_0.5/simplex J=4
    - CSG_MDRUN_STEPS=500 TEST=propane/ibi J=4
    - CSG_MDRUN_STEPS=5000 TEST=propane/imc J=4
    - CSG_MDRUN_STEPS=500 TEST=spce/cma/density J=4
    - CSG_MDRUN_STEPS=500 TEST=spce/cma/simple J=4
    - CSG_MDRUN_STEPS=500 TEST=spce/ibi J=4
    - CSG_MDRUN_STEPS=500 TEST=spce/ibi_pressure J=4
    - CSG_MDRUN_STEPS=5000 TEST=spce/imc J=4
    - CSG_MDRUN_STEPS=5000 TEST=spce/realtime J=4
    - CSG_MDRUN_STEPS=2500 TEST=spce/re J=4
    - CSG_MDRUN_STEPS=500 TEST=spce/simplex/density J=4
    - CSG_MDRUN_STEPS=500 TEST=spce/simplex/pressure J=4
    - CSG_MDRUN_STEPS=500 TEST=spce/simplex/simple J=4
    - CSG_MDRUN_STEPS=500 TEST=urea-water/ibi J=4
    - CSG_MDRUN_STEPS=500 TEST=urea-water/kb-ibi J=4
    - CSG_MDRUN_STEPS=500 TEST=urea-water/cibi J=4
    - CSG_MDRUN_STEPS=500 TEST=urea-water/cibi/pre J=4
    - CSG_MDRUN_STEPS=500 TEST=LJ1-LJ2/imc J=4

before_script:
  - rm -vrf * .git
  - wget https://raw.githubusercontent.com/votca/buildutil/master/build.sh && chmod 755 build.sh
  - mkdir -p "$HOME/votca/src"
  - if [[ ${MINIMAL} != yes ]]; then 
      wget -qO- https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${HDF5_VERSION}/src/hdf5-${HDF5_VERSION}.tar.gz | tar -xz &&
      cd hdf5-${HDF5_VERSION} && ./configure --prefix=$HOME/hdf5 && make -j4 &> /dev/null && make install && cd ..;
    fi
  - if [[ ${GMX_VERSION} = 9999 ]]; then
      CMAKE_VERSION=3.4.3-Linux-x86_64 &&
      wget --no-check-certificate -qO- http://www.cmake.org/files/v${CMAKE_VERSION:0:3}/cmake-${CMAKE_VERSION}.tar.gz | tar -xz &&
      export CMAKE="$PWD/cmake-${CMAKE_VERSION}/bin/cmake" ;
    fi
  - if [[ ${MAN} ]]; then git clone --depth=1 https://github.com/votca/doxygen.git "$HOME/votca/src/devdoc"; fi 
  - if [[ ${GVER} ]]; then export CC=gcc-${GVER}; export CXX=g++-${GVER}; fi

script:
  - PATH="$HOME/hdf5:$PATH" ./build.sh -Wu $([[ ${TRAVIS_BRANCH} = stable ]] || echo "--dev") --prefix "$HOME/votca"
    ${TYPE:+-DCMAKE_BUILD_TYPE=${TYPE}}
    ${TEST:+--runtest=$TEST} ${WERROR:+--warn-to-errors} -DWITH_H5MD=ON ${MINIMAL:+--minimal} ${MAN:+--devdoc}
    ${J:+-j$J} ${BDIR:+--builddir=$BDIR} ${NINJA:+--ninja} ${WALL:+--Wall} ${GMX_VERSION:+--gmx-release ${GMX_VERSION}}
    --directory "$HOME/votca/src" --no-clean --depth 1 -DGMX_USE_RDTSCP=OFF ${GMX_DOUBLE:+-DGMX_DOUBLE=yes}
    tools $([[ ${MINIMAL} ]] || echo gromacs) csg csgapps ${MAN:+csg-manual} ${TEST:+csg-tutorials}
    ${CTP:+kmc moo ctp} ${XTP:+moo ctp xtp}

after_success:
  - if [[ ${MAN} && ${CC} = gcc* ]]; then
      cp "$HOME"/votca/src/{csg-manual,devdoc}/manual.pdf;
      cd "$HOME/votca/src/devdoc";
      if [[ ${TRAVIS_BRANCH} = master && ${encrypted_3780e1dc437f_key} && ${encrypted_3780e1dc437f_iv} && ${TRAVIS_PULL_REQUEST} == false ]]; then
        git config --global user.name "Automatic Deployment (Travis CI)";
        git config --global user.email "votca-commits@googlegroups.com";
        git add --all && git commit -m "Documentation Update";
        openssl aes-256-cbc -K $encrypted_3780e1dc437f_key -iv $encrypted_3780e1dc437f_iv -in deploy.enc -out ~/.ssh/id_rsa -d;
        chmod 600 ~/.ssh/id_rsa;
        git push git@github.com:votca/doxygen.git gh-pages;
      else
        git diff --no-color | head -n 500;
      fi;
    fi

cache:
  - ccache

compiler:
  - gcc

notifications:
  email:
    recipients: #encrypted votca-commits@googlegroups.com so that fork don't notify us (travis-ci/travis-ci#6100)
      secure: yAYhUIO6l2FKfapQNhde+nTH2tGbOj4yWgzcYXyw8Hw/mtZ84uShUeB7asGklr0JFQ8zXw7vg1HT1a2uU09OCx2RcKXnlJ66yFRnBqvzC80yTxlJhYjJsHSXo5/pmT5d045k6WTH3IxHc9Flx2szbavQPz/HLxxI+fN4kfNJxtOVghiQqlUdNDEnwq1raliPOAxS/ANQt3phPmrZUS7I/QGfEOQlwEzzgV7NWPpwR3L83hIfu4dOM5FTFkKHqXQXxjMxvI1KnEr8o+yU7m/l4ruYkEw8Axsnd4NjiF8JsWPZOkee24+cspRl6bTgTb3w7l4beuWTfcQKg8svGeeoMM5RWjwZJnUhYywSwkuMdeeZ5i0RJAIbq1tcoWYSL5KdwGs3NPLu1J1OR3ArUUXFVN/m7njgnr/3XRNx5tXYZ9A1blAMBTAFMzik3yKhERA4QJz9aUXZEwfPQ1FTZEuYm8fhnY5+n+NgKzXgLPbVcgAxoTmseSf+rnvZXltlX6Dxql09iqGhxJlRBw8PJuepFf+J+wU28g+dcm6N8U/TNTOCmO6WgqKw/65Hbv8Xhd6pMC/oTVeal20GRT1dUBAgG2sb0Ht9jX56G+WZ0GRUr1vYMONvEX3NNiIHyyA8iGOpBL/+P1TOucXYyKNZcfV10NugUO2NevPny54vQr2kDnA=
